sudo: false

os:
  - osx
  - linux

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi
  - if [ $TRAVIS_OS_NAME == "osx" ]; then
      brew install yarn --without-node;
    fi
  - npm i -g npm@5.10.0

install:
  - yarn
  - yarn vscode:prepublish
  - npx copy-dir-cli ./src/test/workspace ./out/test/workspace
  - yarn --cwd ./src/test/workspace

script:
  - yarn test --silent

cache:
  yarn: true