pull_requests:
  do_not_increment_build_number: true
build:
  verbosity: minimal

install:
  - ps: Install-Product node 18.0 x64
  - npm install -g yarn
  - npm install -g mocha

build_script:
  - yarn
  - yarn vscode:prepublish

test_script:
  - node --version
  - yarn --version
  - yarn test
