pull_requests:
  do_not_increment_build_number: true
build:
  verbosity: minimal

install:
  - ps: Install-Product node 6.5.0 x64
  - npm install -g yarn
  - npm install -g npm@5.10.0
  - npm install -g mocha 

build_script:
  - yarn
  - yarn vscode:prepublish
  - npx copy-dir-cli ./src/test/workspace ./out/test
  - yarn --cwd ./src/test/workspace

test_script:
  - node --version
  - yarn --version
  - yarn test